### ISSUE TITLE
Beam SQL source/sink support

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#2127]
This is to track Beam source/sink's support for Beam SQL `Schema` & `Row` that we want.

## Avro

We can easily convert between `org.apache.avro.Schema` and `org.apache.beam.sdk.schemas.Schema` and between `org.apache.avro.generic.GenericRecord` and `org.apache.beam.sdk.values.Row`. (see `org.apache.beam.sdk.schemas.utils.AvroUtils`).

Based on that, it's fairly easy to convert from `GenericRecord` to case classes without having to generate code by leveraging the work we've done on `To`.

### Tasks

- [ ] Implement a new `AvroIO` that reads `GenericRecord` into `Row`, case classes or java beans
- [ ] Implement a `check` method that validate the compatibility between an  avro `Schema` and a beam `Schema`, or a avro `Schema` and a type given its (implicit) beam `Schema`.
- [ ] Some schema transformations need to be supported for things like case convention. ex: fields in avro are usually using snake_case, while case classes we usually use camelCase. The IO / check methods should provide some flexibility.

## BigQuery

BQ can read Avro generic records which means that we can leverage the schema based `AvroIO` and essentially get the same benefits. If it works well, it might be possible to deprecate all the BQ macros.

BQ can only write `TableRow` though, so we need `Schema` & `Row` to BQ `TableSchema` & `TableRow` conversion.

### Tasks

- [ ] Implement a `check` method that validate the compatibility between a table schema and a beam `Schema`, or a table schema and a type given its (implicit) beam `Schema`.
- [ ] Integrate with the direct storage API. If we know the `Schema`of a class, it should be fairly easy to automatically push back the list of fields to read in `withReadOptions`.
- [ ] BQ SQL queries support ? 

## TF.Example

Similar to Avro ?

## JDBC (?)

No idea. Do we even want this ?

**Comment by nevillelyh** [comment]
@jto can you fill in the details?

**Comment by jto** [comment]
## Avro

We can easily convert between `org.apache.avro.Schema` and `org.apache.beam.sdk.schemas.Schema` and between `org.apache.avro.generic.GenericRecord` and `org.apache.beam.sdk.values.Row`. (see `org.apache.beam.sdk.schemas.utils.AvroUtils`).

Based on that, it's fairly easy to convert from `GenericRecord` to case classes without having to generate code by leveraging the work we've done on `To`.

### Tasks

- [ ] Implement a new `AvroIO` that reads `GenericRecord` into `Row`, case classes or java beans
- [ ] Implement a `check` method that validate the compatibility between an  avro `Schema` and a beam `Schema`, or a avro `Schema` and a type given its (implicit) beam `Schema`.
- [ ] Some schema transformations need to be supported for things like case convention. ex: fields in avro are usually using snake_case, while case classes we usually use camelCase. The IO / check methods should provide some flexibility.

## BigQuery

BQ can read / write generic records which means that we can leverage the schema based `AvroIO` and essentially get the same benefits. If it works well, it might be possible to deprecate all the BQ macros.

### Tasks

- [ ] Implement a `check` method that validate the compatibility between a table schema and a beam `Schema`, or a table schema and a type given its (implicit) beam `Schema`.
- [ ] Integrate with the direct storage API. If we know the `Schema`of a class, it should be fairly easy to automatically push back the list of fields to read in `withReadOptions`.
- [ ] BQ SQL queries support ? 

## TF.Example

Similar to Avro ?


## JDBC (?)

No idea. Do we even want this ?

**Comment by nevillelyh** [comment]
Some update:

- Avro
  - `Schema`/ `Row` <=> Avro `Schema`/`GenericRecord` conversion already exists.
  - `AvroTableProvider` is missing [BEAM-7920](https://issues.apache.org/jira/browse/BEAM-7920).
- BigQuery
  - `Schema`/ `Row` conversion already exists, `GenericRecord` for read, `TableRow` for write.
  - `BigQueryTableProvider` exists but seems to support read from table only. It'll be nice to support Storage API reads [BEAM-7922](https://issues.apache.org/jira/browse/BEAM-7922).
- TF.Example
  - Need to implement `Schema`/`Row` conversion and `TensorFlowTableProvider` [BEAM-7921](https://issues.apache.org/jira/browse/BEAM-7921).

**Comment by jto** [comment]
@nevillelyh seems that it won't happen. Close issue ?
