### ISSUE TITLE
Beam 2.0.0 checklist

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#501]
Checklist for when Beam 2.0.0 is released
- [x] Use new TensorFlow TFRecordIO
- [x] Remove BigtableIO monkey patch
- [x] Verify that #480 is fixed (rav)
- [x] Breaking BigQuery changes
- [x] IO channel changes
- [x] Breaking file system BEAM-59 #600
- [x] Breaking Coder API
- [x] Side inputs broken
- [x] Side outputs broken
- [x] Metrics API
- [x] InMemory Sink broken
- [x] Scio HDFS module (make sure it's registered with the new FS API) (#686)
- [x] Windowing behavior/API might have changed
