### ISSUE TITLE
Beam 2.1.0 checklist

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/scio#633]
- [x] Remove patched `PubsubIO.java`
- [x] Remove `auto-value` dependency in `scio-core` (was needed for `PubsubIO` patch)
(https://issues.apache.org/jira/browse/BEAM-1377)
- [x] NPE when writing an empty table to BigQuery [BEAM-2406](http://issues.apache.org/jira/browse/BEAM-2406)
