### ISSUE TITLE
Beam 2.2.0 checklist

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#797]
- [x] Verify Serializable TableSchema Supplier in BigQuerySourceBase [BEAM-2532](https://issues.apache.org/jira/browse/BEAM-2532) (probably in Beam 2.2.0)
- [x] Coder precedence [BEAM-2658](https://issues.apache.org/jira/browse/BEAM-2658) (probably in Beam 2.2.0)
- [x] Avro metadata when splitting [BEAM-2628](https://issues.apache.org/jira/browse/BEAM-2628) (probably in Beam 2.2.0)
- [x] Remove patched `BigtableIO` classes and `auto-value` in `scio-bigtable`  (pending bigtable-client-core dependency, still 0.9.7.1 in `beam:master`)
- [ ] ~`Sample.any` performance fix [BEAM-3247](https://issues.apache.org/jira/browse/BEAM-3247) apache/beam#4175~
