### ISSUE TITLE
Beam 2.3.0 checklist

### ISSUE THREAD

**Issue by nevillelyh** [spotify/scio#946]
- [x] `Sample.any` performance fix [BEAM-3247](https://issues.apache.org/jira/browse/BEAM-3247) apache/beam#4175
- [x] #998 `ClosureTest` failure
- [x] #948 Consolidate `HadoopFileBasedSink` in Parquet IO with Beam
- [x] #997 IllegalMutationException in `LibSVMTest`
- [x] #996 IllegalMutationException in `FileDownloadDoFnTest`
- [x] Update Java examples (after they tag the release commit)

**Comment by nevillelyh** [comment]
Pushed to https://github.com/spotify/scio/tree/beam-2.3.0
All done pending Beam 2.3.0 release.
